### ISSUE TITLE
The demo `serviceUrl` should work with `wss`

### ISSUE THREAD

**Issue by thesunny** [stackiva/slate-collaborate-support#11]
Currently, when trying to access the demo collaborative server endpoint here:

`ws://ec2-184-72-124-41.compute-1.amazonaws.com:8080`

It works fine. But if we use the `wss` version

`wss://ec2-184-72-124-41.compute-1.amazonaws.com:8080`

It fails with this error

```
713-77772e135279bde72aff.js:1 WebSocket connection to 'wss://ec2-184-72-124-41.compute-1.amazonaws.com:8080/' failed: 
```

I this this adjustment would need to be made in conjunction with adding the subdomain and the certificate for it.

**Comment by wleroux** [comment]
Added the demo environment behind a load balancer and configured the SSL certificate for it. You can now connect to either `ws://demo.stackiva.com` or `wss://demo.stackiva.com/` :)
