### ISSUE TITLE
Bug in undo/redo

### ISSUE THREAD

**Issue by PaddyMann** [stackiva/slate-collaborate-support#13]
3 issues probably relating to a single bug:

- I'm able to undo more operations than I've actually performed
- If I then redo, the editor crashes
- If I then refresh the page, the editor goes into a weird loop

See https://www.loom.com/share/85d978393b754915a496f858e7cedce5

**Comment by wleroux** [comment]
Looking into it. From a basic editor perspective I cannot reproduce it. Will be trying to see if I can recreate it using different browsers. It might also be an issue with the forced layout (this shouldn't be the case, but it's the other factor that is different from my test case.)

**Comment by wleroux** [comment]
Can you check that you are not using two history systems together? These symptoms look a lot like using `withHistory` alongside slate collaborate.

**Comment by PaddyMann** [comment]
You're right — withHistory was also active. Good catch and sorry for the false alarm!
