### ISSUE TITLE
Undo undoes the initial selection [Minor]

### ISSUE THREAD

**Issue by PaddyMann** [stackiva/slate-collaborate-support#15]
V minor bug:

- When we load the slate editor, we focus on the editor using:
```
useEffect(() => {
  ReactEditor.focus(editor);
}, []);
```

- With the undo in slate-collaborate, pressing undo will deselect the editor.
- This differs to the Slate's `withHistory` plugin, which will leave the editor selected.

**Comment by wleroux** [comment]
The current design is to undo any changeset (selection included). Changing the design to undo changes only if there is a mutation to the value is a simple enhancement to the existing design. Will do!

**Comment by wleroux** [comment]
Completed in 0.0.21
