### ISSUE TITLE
onUserSessionEnd and onDocumentSessionEnd never get called

### ISSUE THREAD

**Issue by PaddyMann** [stackiva/slate-collaborate-support#16]
Expected behavior: 
- onUserSessionEnd gets called after closing a web browser with a document editor open
- onDocumentSessionEnd gets called after closing all web browsers with document editors open

Neither seem to get called at all.

**Comment by wleroux** [comment]
Will look into this soon.

**Comment by wleroux** [comment]
Resolved the issue in `0.0.14`.

There is still a related issue that will be resolved in #3 however. When a service is terminated while subscriptions still exist, the new services (or other service nodes) are not aware that the session is defunc and will not call the `onUserSessionEnd` and `onDocumentSessionEnd` API calls. As part of the larger work involved in #3, this will be resolved.
