### ISSUE TITLE
Consider changing the `status` value options in the Slate Collaborate Plugin

### ISSUE THREAD

**Issue by thesunny** [stackiva/slate-collaborate-support#22]
Currently there is no way to tell, in the Slate Collaborate Plugin, whether we are in "read" mode or "read-write" mode.

Consider changing the `status` value options to be:

*   NO\_SESSION
*   LOST\_SESSION
*   CONNECTING
*   RECONNECTING
*   READ
*   READ\_WRITE

and removing READY.

I'm open to other options as far as naming goes.

**Comment by wleroux** [comment]
Updated code to provide status with distinct read and read-write state.
