### ISSUE TITLE
`value` returned by `useSlateCollaborate` should be of type `Descendant`

### ISSUE THREAD

**Issue by thesunny** [stackiva/slate-collaborate-support#28]
Currently `useSlateCollaborate` returns a `value` with a type `Node[]`.

The `value` needs to be passed to `<Slate value={value} />` which expects value to be of type `Descendant[]`. Because it is of type `Node[]` instead, we get a typing error.

**Comment by wleroux** [comment]
Issue has been resolved in `0.0.22`
