### ISSUE TITLE
The public slate-collaborate demo environment should be on a fixed domain name

### ISSUE THREAD

**Issue by wleroux** [stackiva/slate-collaborate-support#6]

**Comment by thesunny** [comment]
The Slate Collaborate plugin must connect to a `serviceUrl`. For our home page and for users that want to take collaborate for a quick spin, we provide them with a temporary `serviceUrl`. Currently, this `serviceUrl` points to an EC2 endpoint, but the endpoint will change if the server is ever rebooted.

The purpose of this change is to attach a fixed domain that we can refer to that won't change after a reboot.

**Comment by wleroux** [comment]
@thesunny Did we have a preference for the sub-domain name? Thinking of setting this up using the `demo` sub-domain.

**Comment by wleroux** [comment]
Updated the DNS entry so that `demo.stackiva.com` is a valid end-point for the demo environment.
