### ISSUE TITLE
Allow slate-collaborate to be used against our demo environment without requiring access set-up

### ISSUE THREAD

**Issue by wleroux** [stackiva/slate-collaborate-support#8]

**Comment by thesunny** [comment]
For clarity, this means that the @slate-collaborate/api and @slate-collaborate/plugin NPM repositories shall be published as public through not open source.

**Comment by thesunny** [comment]
Hi @wleroux, when you close the issue, can you put a comment on why it was closed. I assume this was completed, but I think it may be unclear for users that are following the issue. Thank you.

**Comment by wleroux** [comment]
Converted the npm packages `@slate-collaborate/api`, `@slate-collaborate/plugin`, and `@slate-collaborate/slate-ot-type` to from `private` to `public`.
